### ISSUE TITLE
Integrating Stapel with History.js

### ISSUE THREAD

**Issue by jacekjagiello** [codrops/Stapel#1]
Hello Pedro Botelho, hello codrops!
Some of Your experimental jQuery plugins use History.js(Gamma Gallery or flipboard layout). It would be amazing, if you'll integrate history.js with Stapel in next script updates. I tried to do it myself, but I don't know too well Javascript and jQuery, it's really hard for me :(

**Comment by botelho** [comment]
Thanks! I will have that in mind.
