### ISSUE TITLE
A gallery with ',' at the name

### ISSUE THREAD

**Issue by hosmelq** [codrops/Stapel#2]
Hello codrops,
I try to keep a gallery with ',' in the name, which I generate two galleries.
Gallery 1, Gallery 2.

![Captura de pantalla de 2012-12-11 14:48:02](https://f.cloud.github.com/assets/1166143/6756/dae0b9b6-43d4-11e2-8235-405aa34eea66.png)

**Comment by botelho** [comment]
Yes, commas are used to separate galleries. That's not a bug. An item can be in more than one gallery. Cheers
