### ISSUE TITLE
Max number of pictures

### ISSUE THREAD

**Issue by VonD** [codrops/Stapel#3]
Hi,

First of all thanks a lot for this great plugin!

Do you have an idea of roughly how many pictures would max be a good fit for this plugin ?

A few criteria would be:
- how fast the page loads
- the page shouldn't "freeze"
- if transitions between piles and pictures remain fluid

Thanks a lot

**Comment by Soraph** [comment]
This question can't be answered, it depends on the browser and the device that is currently used
